### ISSUE TITLE
https://github.com/uWaterloo/Datasets/tree/master/Sites is out of date / depricated

### ISSUE THREAD

**Issue by nathanv** [uWaterloo/Datasets#163]
It's been deprecated for using WCMS directly.

**Comment by nathanv** [comment]
@KartikTalwar should we keep this up to date or should we just delete?

**Comment by KartikTalwar** [comment]
@nathanv the API still uses the csv for the list. Let's replace the api with the official wcms list first and then we can remove this.

cc @zachomedia
