### ISSUE TITLE
Building's parent is itself

### ISSUE THREAD

**Issue by wtyanan** [uWaterloo/Datasets#258]
Hi, I'm trying to sort out all parent buildings. But some of the buildings (that have latitude and longitude) has their selves as their own parent. (e.g. REN, id 822). Is this intentional?

**Comment by sbobkin** [comment]
Hi @wtyanan - the building data you're looking at is a collection of information put together by the open data team and the campus community. In the future, this building data set will be classified as crowd data and have appropriate guarantees about it's quality and accuracy. 

For now I believe that relationship is correct, but you're more than welcome to submit a pull request with updated information.
