### ISSUE TITLE
Add Publicly Accessible Microwave locations data

### ISSUE THREAD

**Issue by nathanv** [uWaterloo/Datasets#53]
Locations are posted to http://www.reddit.com/r/uwaterloo/wiki/microwaves but not georeferenced. Would love if someone out in the community curated this. Format could be something like https://github.com/uWaterloo/Datasets/blob/master/CoffeeAndDonutShops/cndlocations.csv

**Comment by nathanv** [comment]
https://github.com/uWaterloo/Datasets/blob/add-microwaves/Microwaves/Microwaves.csv

It's not ready for a pull request. Working on it when I have a bit of free time. @jmtjendra can you help to get the data set on par with the reddit site? Thereafter, we should audit the data to see if we can post it to open data.

To Dos:
Steps
1. [ ] Start editing Microwaves.csv collaboratively
1. [ ] Complete Microwaves.csv (first run)
1. [ ] Audit Microwaves by building survey and sending it to clients
1. [ ] Design api schema; should we make it less flat? --> convert to geoJSON
1. [ ] Once schema is approved deploy to api

**Comment by jmtjendra** [comment]
I can work on this on my free time as a side project. However, I know that there is at least one inaccuracy: In EV1, I remember seeing at least 2 microwaves. 

Also, some are for "staff only" and by putting it out to public (and on campus map), we might stir up some conflict with those departments. How should we handle this?

**Comment by nathanv** [comment]
I say we only merge the data in to master branch if we have clearance from the people who run the microwave.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: jmtjendraSent: Tuesday, June 9, 2015 16:27To: uWaterloo/DatasetsReply To: uWaterloo/DatasetsCc: Nathan VexlerSubject: Re: [Datasets] Add Publicly Accessible Microwave locations data (#53)I can work on this on my free time as a side project. However, I know that there is at least one inaccuracy: In EV1, I remember seeing at least 2 microwaves. 

Also, some are for "staff only" and by putting it out to public (and on campus map), we might stir up some conflict with those departments. How should we handle this? 

—Reply to this email directly or view it on GitHub.

**Comment by jmtjendra** [comment]
https://github.com/uWaterloo/Datasets/blob/master/PointsOfInterest/microwave_locations.csv
