### ISSUE TITLE
Stale data for employer info sessions 

### ISSUE THREAD

**Issue by steviek** [uWaterloo/Datasets#82]
Still returns data for Spring 2014

**Comment by nathanv** [comment]
We will look at it as soon as we can. There are some other priorities at the moment but we will fix it soon. ‎Thank you for reporting. Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                                         From: Steven KideckelSent: Tuesday, January 6, 2015 10:14To: uWaterloo/DatasetsReply To: uWaterloo/DatasetsSubject: [Datasets] Stale data for employer info sessions  (#82)Still returns data for Spring 2014

—Reply to this email directly or view it on GitHub.

**Comment by KartikTalwar** [comment]
@steviek new data is now up! You can access them at 

https://api.uwaterloo.ca/v2/terms/1151/infosessions.json
