### ISSUE TITLE
Add locker locations to Open Data

### ISSUE THREAD

**Issue by nathanv** [uWaterloo/Datasets#90]
Inspired by http://www.reddit.com/r/uwaterloo/comments/2y907m/locker_to_store_guitar_on_campus/

Pros: locations of lockers for students.
Cons: could give thieves a shopping list of where to go to cut locks and steal things.

**Comment by nathanv** [comment]
@KartikTalwar what do you think about just starting a simple CSV which we can then create a method for later as it gains steam?

**Comment by KartikTalwar** [comment]
@nathanv yeah, if theres a csv we can start compiling, we can definitely serve it upstream

**Comment by nathanv** [comment]
@KartikTalwar Even better news! /u/lunrSabr94 on reddit [volunteered to take point on curating the data](http://www.reddit.com/r/uwaterloo/comments/2y907m/locker_to_store_guitar_on_campus/cpdbp35?context=3)!

**Comment by KartikTalwar** [comment]
Awesome!
